FROM tensorflow/tensorflow:2.2.0-gpu

ARG DEBIAN_FRONTEND=noninteractive

# Install apt dependencies
RUN apt-get update && apt-get install -y \
    vim \
    git \
    gpg-agent \
    python3-cairocffi \
    protobuf-compiler>=3.12.0 \
    python3-pil>=6.2.0 \
    python3-lxml \
    python3-tk \
    imagemagick \
    libsm6 \
    libxext6 \
    libxrender-dev \
    wget  

# Install gcloud and gsutil commands
# https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu
RUN export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y

# Add new user to avoid running as root
RUN useradd -ms /bin/bash tensorflow
USER tensorflow
WORKDIR /home/tensorflow

# ------------------------------------------------------------------------------- #
# 아래는 이미지 자체에서 models를 다운받았을 때 진행한다.                                   #
# 호스트에서 models 다운받아 docker volume으로 연결 시에는 Container 생성 후,              #
# root로 Container에 들어가서(docker exec -it -u 0 이미지명 /bin/bash) 하나하나 실행한다.  #
# ------------------------------------------------------------------------------- #

# Copy this version of of the model garden into the image  => Replace as volume connection btw. host and container.
#RUN git clone https://github.com/tensorflow/models.git /home/tensorflow/models

# Compile protobuf configs
#WORKDIR /home/tensorflow/models/research/
#RUN protoc object_detection/protos/*.proto --python_out=.

#RUN cp object_detection/packages/tf2/setup.py ./
#ENV PATH="/home/tensorflow/.local/bin:${PATH}"

#RUN python -m pip install -U pip
#RUN python -m pip install .

#RUN pip install ipython
#RUN pip install opencv-python
#RUN pip install opencv-contrib-python
#RUN pip install imageio

# Tensorflow log filtering. default : 0 (show all logs), 1 : filter INFO logs, 2 : filter WARNING logs, 3 : filter ERROR logs.
ENV TF_CPP_MIN_LOG_LEVEL 3

